{{- $global := .Values.global -}}
{{- $SARole := .Values.global.SARole -}}
{{- range $key, $values := .Values.deployments }}
{{- range $msgServiceDetails := $values }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ $global.namespace }}-iflyloyalty-app-sa
  name: {{ $global.namespace }}-iflyloyalty-app-sa
  namespace : {{ $global.namespace }}
  {{- if ne $SARole "" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{$global.SARole}}"
  {{- end }}
{{- end }}
---
{{- end }}
    