{{- $global := .Values.global -}}
{{- $namespace := .Values.global.namespace -}}
{{- range $key, $values := .Values.deployments }}
{{- range $msgServiceDetails := $values }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ $namespace }}-{{ $msgServiceDetails.deploymentName }}
spec:
  ttlSecondsAfterEmpty: 100
  consolidation:
    enabled: false
  limits:
    resources:
      cpu: {{$msgServiceDetails.cpu_limit}}
  labels:
    namespace: {{ $namespace }}
    service: {{ $msgServiceDetails.nodeLabel }}
  requirements:
    - key: "kubernetes.io/arch" 
      operator: In
      {{ if $msgServiceDetails.nodeArchitecture }} 
      values: ["{{ $msgServiceDetails.nodeArchitecture }}"]
      {{- else }}
      values: ["arm64"]
      {{- end }}  
    - key: "kubernetes.io/os" 
      operator: In
      {{ if $msgServiceDetails.os }} 
      values: ["{{ $msgServiceDetails.os }}"]
      {{- else }}
      values: ["linux"]
      {{- end }}
    - key: "karpenter.sh/capacity-type" 
      operator: In
      {{ if $msgServiceDetails.capacityTypes }} 
      values: ["{{ $msgServiceDetails.capacityTypes }}"]
      {{- else }}
      values: ["on-demand"]
      {{- end }}
    - key: node.kubernetes.io/instance-category
      operator: In
      {{ if $msgServiceDetails.instanceCategories }} 
      values: {{- range $instanceCategory := $msgServiceDetails.instanceCategories }} 
        - {{ $instanceCategory }} 
      {{- end }} 
      {{- else }}
      values:
        - m
      {{- end }}
  providerRef:
    name: {{ $namespace }}-nodetemplate
{{- end }}
---
{{- end }}  